### PR TITLE
change 2018 enr skip lines to 1 

### LINKED ISSUE #133: resolve test issue
─ 5. Error: all public aggs, 2017-18 enrollment data (@test_charter.R#129)  ───────────────────────────────────────
Assigned data `as.character(df$program_code)` must be compatible with existing data.

### LINKED ISSUE #135: fetch_enr breaks for args (2018, tidy = TRUE)
```
devtools::install_github('almartin82/njschooldata')
library(njschooldata)
foo <- fetch_enr(2018, TRUE)
```

returns

```
Error: Assigned data `as.character(df$program_code)` must be compatible with existing data.
x Existing data has 26484 rows.
x Assigned data has 0 rows.
i Only vectors of size 1 are recycled.

In addition: Warning message:
Unknown or uninitialised column: `program_code`. 
```

### PR DESCRIPTION
**Pull request by chiouey**
2018 enrollment file went from headers in 3rd row to headers in 2nd row -- lol

resolves #133; resolves #135

### CODE REVIEW

File: R/enr.R [hunk 1]
```diff
@@ -30,9 +30,12 @@ get_raw_enr <- function(end_year) {
       enr <- gdata::read.xls(
         this_file, sheet = 1, header = TRUE, stringsAsFactors = FALSE
       )
-      # if 2018 skip 3 lines
-    } else if (end_year >= 2018) {
-      enr <- readxl::read_excel(this_file, skip = 2)
+      # ~~if 2018 skip 3 lines~~
+      # the number of 2018 skip lines is decreasing -- it's 1 now
```
Comment (almartin82) [inline R/enr.R:34]: 🤷‍♂️
